# spring.application.name=backend
#  config port
server:
  port: 8080
  servlet:
    context-path: /nova_beauty
  tomcat:
    max-swallow-size: 200MB

#  Config cau hinh database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nova_beauty
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # Chi dung jpa duoi day de tu dong tao table User, tuy nhien khi di lam can dua vao 1 script SQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  # validate: Hibernate chi kiem tra cac bang, cot, kieu du lieu trong DB co phu hop voi entity trong code hay không. Neu khong khop → bao loi, khong tu sua.
  # update : Hibernate so sanh entity va DB → tu dong them hoac chinh sua bang/cot de khop. Tuy nhien, no khong xoa cac cot cu.
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

#  Brevo Email Configuration
brevo:
  api:
    key: ${BREVO_API_KEY_NOVA:change-me}
  sender:
    email: ${BREVO_EMAIL} # Email đã verify trong Brevo

#  Secret Key
jwt:
  signerKey: "/nvphzRqEgduNfnKy2ztU3XBeojbmK8jzDivxOxLIGnl+D5GfkjyXdLq15xz9af/\n"
  valid-duration: 3600  # in second
  refreshable-duration: 360000 # in seconds

app:
  frontend:
    base-url: "http://localhost:8080/nova_beauty"

# GHN shipment configuration
ghn:
  token: ${GHN_TOKEN}
  shop-id: ${GHN_SHOP_ID}
  base-url: https://dev-online-gateway.ghn.vn

# Momo payment configuration
momo:
  # Thông tin tích hợp MoMo sandbox (có thể thay bằng thông tin tài khoản của bạn)
  partner-code: MOMOLRJZ20181206
  return-url: "http://localhost:3000/order-success"
  end-point: "https://test-payment.momo.vn/v2/gateway/api"
  # Lưu ý: context-path của backend là /nova_beauty nên IPN URL cần kèm context-path
  ipn-url: "http://localhost:8080/nova_beauty/api/momo/ipn-handler"
  access-key: "mTCKt9W3eU1m39TW"
  secret-key: "SetA5RDnLHvt51AULf51DyauxUo3kDU6"
  request-type: "captureWallet"

# Layer1 - Controller: Quan ly cac mapping, endpoint
# Layer2 - Service: Xu ly cac logic lien quan toi subdomain
# Layer3 - Repository: Tang tuong tac truc tiep voi DBMS
